// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function EmitTestEvent():Promise<void>;

export function GetMachines():Promise<Array<models.Machine>>;

export function GetUsers():Promise<Array<models.User>>;

export function Greet(arg1:string):Promise<string>;

export function LogEmiter(arg1:string,arg2:string):Promise<void>;

export function SyncHalls():Promise<boolean>;

export function SyncUserHalls():Promise<boolean>;

export function SyncUsers():Promise<boolean>;
