// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetHalls():Promise<Array<models.Machine>>;

export function Greet(arg1:string):Promise<string>;
