// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitTestEvent() {
  return window['go']['backend']['App']['EmitTestEvent']();
}

export function GetMachines() {
  return window['go']['backend']['App']['GetMachines']();
}

export function GetUsers() {
  return window['go']['backend']['App']['GetUsers']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function LogEmiter(arg1, arg2) {
  return window['go']['backend']['App']['LogEmiter'](arg1, arg2);
}

export function Stage() {
  return window['go']['backend']['App']['Stage']();
}

export function SyncHalls() {
  return window['go']['backend']['App']['SyncHalls']();
}

export function SyncProducts() {
  return window['go']['backend']['App']['SyncProducts']();
}

export function SyncUserHalls() {
  return window['go']['backend']['App']['SyncUserHalls']();
}

export function SyncUsers() {
  return window['go']['backend']['App']['SyncUsers']();
}
