name: Release Windows App

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Windows App
    runs-on: windows-latest
    environment: BETA
    strategy:
      matrix:
        platform:
          - windows/amd64
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable


      - name: Create EnvFile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DB_HOST: ${{secrets.DB_HOST}}
          envkey_DB_PORT: ${{secrets.DB_PORT}}
          envkey_DB_USER: ${{secrets.DB_USER}}
          envkey_DB_PASS: ${{secrets.DB_PASS}}
          envkey_DB_NAME: ${{secrets.DB_PASS}}
          envkey_BC_HOST: ${{secrets.BC_HOST}}
          envkey_BC_BASIC_AUTH: ${{secrets.BC_BASIC_AUTH}}
          envkey_DEBUG: ${{secrets.DEBUG}}
          envkey_STAGE: ${{secrets.STAGE}}
          file_name: config.env
          fail_on_empty: true
          sort_keys: true
          directory: config
          
      - name: Install wails
        shell: bash
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build Windows portable app
        shell: bash
        run: |
          CGO_ENABLED=1 wails build -clean -platform ${{ matrix.platform }} \
          -webview2 embed 
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: build/bin

